/**
 * B-roll source registry — the provider-agnostic catalogue behind the picker.
 *
 * Every source is described by data, never by code branches in the UI. Adding a
 * provider means adding one entry here (plus, if it needs a key, one adapter in
 * the `stock-search` edge function). The UI reads this list to decide what to
 * show, what to enable, and what licence text to display.
 *
 * Why the re-host policy matters
 * ------------------------------
 * Directorr composites assets on a <canvas> and pipes it to MediaRecorder, so
 * an asset MUST be same-origin or served with `Access-Control-Allow-Origin`.
 * That makes "store a copy in the ephemeral bucket" the only universally safe
 * strategy — and it happens to be what the licences ask for:
 *
 *   allowed     — re-hosting is permitted (Pexels). We store a copy anyway.
 *   required    — hotlinking is forbidden, a copy is mandatory (Pixabay).
 *   prohibited  — a copy is forbidden and hotlinking taints the canvas
 *                 (Unsplash), so the source cannot be offered at all.
 *
 * See docs/SETUP-BROLL.md for the key-handling story.
 */

export const REHOST_POLICY = {
  NOT_NEEDED: 'not-needed',
  ALLOWED: 'allowed',
  REQUIRED: 'required',
  PROHIBITED: 'prohibited',
};

export const SOURCES = [
  {
    id: 'studio',
    label: 'Studio library',
    blurb:
      'Licence-free stills and loops generated for Directorr and served from this origin. No key, no CORS risk, no expiry.',
    kinds: ['image', 'video'],
    firstParty: true,
    searchable: false,
    requiresKey: false,
    rehostPolicy: REHOST_POLICY.NOT_NEEDED,
    license: 'CC0 / public domain — generated by Directorr, no attribution required',
    attribution: 'Directorr Studio Library',
    enabled: true,
  },
  {
    id: 'upload',
    label: 'Your upload',
    blurb: 'A file from your device. You are responsible for holding the rights to it.',
    kinds: ['image', 'video', 'audio'],
    firstParty: true,
    searchable: false,
    requiresKey: false,
    rehostPolicy: REHOST_POLICY.NOT_NEEDED,
    license: 'Creator-supplied — you own the rights',
    attribution: '',
    enabled: true,
  },
  {
    id: 'url',
    label: 'Paste a URL',
    blurb:
      'Any direct link to an image, video, or audio file. We download it and store our own copy — hotlinks are never drawn to the canvas.',
    kinds: ['image', 'video', 'audio'],
    firstParty: false,
    searchable: false,
    requiresKey: false,
    rehostPolicy: REHOST_POLICY.ALLOWED,
    license: 'Unverified — you are responsible for the rights to this file',
    attribution: '',
    enabled: true,
  },
  {
    id: 'pexels',
    label: 'Pexels',
    blurb: 'Free stock photos and video, strong on real-world B-roll. Re-hosting is permitted.',
    kinds: ['image', 'video'],
    firstParty: false,
    searchable: true,
    requiresKey: true,
    keyName: 'PEXELS_API_KEY',
    rehostPolicy: REHOST_POLICY.ALLOWED,
    license: 'Pexels License — free for commercial use; a prominent credit is expected',
    attribution: 'Media provided by Pexels',
    attributionUrl: 'https://www.pexels.com',
    rateLimit: '200 requests/hour',
    enabled: true,
    docs: 'https://www.pexels.com/api/documentation/',
  },
  {
    id: 'pixabay',
    label: 'Pixabay',
    blurb:
      'Free photos, video, and music under one key. Hotlinking is not allowed, which is exactly what our ephemeral copy does.',
    kinds: ['image', 'video'],
    firstParty: false,
    searchable: true,
    requiresKey: true,
    keyName: 'PIXABAY_API_KEY',
    rehostPolicy: REHOST_POLICY.REQUIRED,
    license: 'Pixabay Content License — free for commercial use, no attribution required (credit appreciated)',
    attribution: 'Media provided by Pixabay',
    attributionUrl: 'https://pixabay.com',
    rateLimit: '100 requests/minute',
    enabled: true,
    docs: 'https://pixabay.com/api/docs/',
  },
  {
    id: 'unsplash',
    label: 'Unsplash',
    blurb: 'Excellent photography, but its API terms conflict with canvas compositing.',
    kinds: ['image'],
    firstParty: false,
    searchable: true,
    requiresKey: true,
    keyName: 'UNSPLASH_ACCESS_KEY',
    rehostPolicy: REHOST_POLICY.PROHIBITED,
    license: 'Unsplash License — free to use, but copies may not be stored',
    attribution: 'Photo by {photographer} on Unsplash',
    attributionUrl: 'https://unsplash.com',
    enabled: false,
    disabledReason:
      'Unsplash requires hotlinking and forbids storing copies, while Directorr must store a copy to draw the frame without tainting the recording canvas. Use Pexels or Pixabay instead.',
    docs: 'https://help.unsplash.com/en/articles/2511245-unsplash-api-guidelines',
  },
];

export const sourceById = (id) => SOURCES.find((source) => source.id === id) || null;

/** Stock hosts -> source id, so a pasted link gets the right licence text. */
const HOST_MAP = [
  [/(^|\.)pexels\.com$/i, 'pexels'],
  [/(^|\.)pixabay\.com$/i, 'pixabay'],
  [/(^|\.)unsplash\.com$/i, 'unsplash'],
];

export function sourceForUrl(url) {
  try {
    const { hostname } = new URL(url);
    const match = HOST_MAP.find(([pattern]) => pattern.test(hostname));
    return match ? sourceById(match[1]) : null;
  } catch {
    return null;
  }
}

/** Sources that need a key-holding endpoint before they can be searched. */
export function keyedSources() {
  return SOURCES.filter((source) => source.searchable);
}
