/**
 * Studio Library loader.
 *
 * The manifest is generated by `npm run library:build` and served from the app's
 * own origin (public/library/). Because these files are first-party they can be
 * composited straight onto the canvas: no key, no CORS negotiation, no taint,
 * and no 7-day expiry. That is what makes the B-roll picker useful before any
 * stock provider is wired up.
 */

const BASE = import.meta.env.BASE_URL || '/';
export const MANIFEST_URL = `${BASE}library/manifest.json`;

const absolute = (file) => new URL(file, `${window.location.origin}${BASE}`).href;

let cache = null;
let inflight = null;

/** Load (and memoise) the studio library. Resolves to `{ assets, license, ... }`. */
export async function loadStudioLibrary() {
  if (cache) return cache;
  if (inflight) return inflight;
  inflight = (async () => {
    const response = await fetch(MANIFEST_URL, { cache: 'force-cache' });
    if (!response.ok) {
      throw new Error(
        `Studio library manifest unavailable (HTTP ${response.status}). Generate it with "npm run library:build".`,
      );
    }
    const manifest = await response.json();
    const assets = (manifest.assets || []).map((item) => ({
      ...item,
      source: 'studio',
      url: absolute(item.file),
      posterUrl: item.poster ? absolute(item.poster) : '',
      license: manifest.license || '',
    }));
    console.log('[stockLibrary] loaded studio library', { assets: assets.length, manifest: MANIFEST_URL });
    cache = { ...manifest, assets };
    return cache;
  })();
  try {
    return await inflight;
  } finally {
    inflight = null;
  }
}
